# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Sheetal_Pipeline_Pool
  demands:
   - agent.name -equals pipeline

steps:
- script: |
    pip install pytest xlrd pytest-html
    pip install -r requirements.txt
    dir
    mkdir c:\report
    pytest tests\win --self-contained-html --html="c:/reports/report.html"
    python myscript.py
    move report1.html c:\\reports
    echo "Automation Execution Finished"
  displayName: 'Run a multi-line script'